### PR TITLE
Initial Working Commit

### PR DESCRIPTION
**Pull request by jtsmedley**
Added test script.
Added node-red configuration and html.
Added index.js with PCA9685 I2C commands (setPwmFrequency, stop, setPwm, setPulse).

### CODE REVIEW

**Comment by telliottosceola** [comment]
@jtsmedley thank you very much for your contribution.

**Comment by jtsmedley** [comment]
Please publish this package to npm.

**Comment by telliottosceola** [comment]
I do not believe this package is currently published to NPM.  It was developed by another engineer who no longer works here.

**Comment by jtsmedley** [comment]
It looks like Jacob and Trey have access to publish.  If you give me access to the npmjs.org website I can set it up for you.

**Comment by zaphod-42** [comment]
Give me a bit and I'll get it published

**Comment by zaphod-42** [comment]
Hey, so I didn't realize what library this was, thanks for your work... we're going to get a board so we can verify its functionality before we publish it to NPM, but we'll get it done asap.

**Comment by telliottosceola** [comment]
Sorry @jtsmedley and @zaphod-42 I haven't been into the office the past day and a half due to bad road conditions so I have not got a board to my desk to test this library with.  I will try to get this done either tomorrow or Friday.

**Comment by jtsmedley** [comment]
@telliottosceola No worries.  I'll try to get my sample flow out in the README tomorrow.  I'm near OKC and in the same boat weather wise.

**Comment by telliottosceola** [comment]
@jtsmedley stay safe!

**Comment by jtsmedley** [comment]
@telliottosceola  Here is a node-red flow for easy use.  The test.js file works as well.

[{"id":"bc7d6333.6da43","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"41aabc6e.0deef4","type":"ncd-pca9685","z":"bc7d6333.6da43","name":"PCA Main","connection":"42258af4.14e0e4","address":"64","frequency":55,"channels":8,"x":620,"y":580,"wires":[["d5bc0685.5cd688"]]},{"id":"d5bc0685.5cd688","type":"debug","z":"bc7d6333.6da43","name":"","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":800,"y":580,"wires":[]},{"id":"86cb8b4b.006f58","type":"inject","z":"bc7d6333.6da43","name":"Get Status","props":[{"p":"topic","vt":"str"}],"repeat":"15","crontab":"","once":false,"onceDelay":0.1,"topic":"get_status","x":130,"y":580,"wires":[["41aabc6e.0deef4"]]},{"id":"ec6c0b82.ff9e98","type":"inject","z":"bc7d6333.6da43","name":"PWM_7","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pwm","payload":"{\"channel\":7,\"pulseOn\":3000,\"pulseOff\":40}","payloadType":"json","x":110,"y":420,"wires":[["41aabc6e.0deef4"]]},{"id":"3a69add6.cd0d72","type":"inject","z":"bc7d6333.6da43","name":"PWM_6","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pwm","payload":"{\"channel\":6,\"pulseOn\":3000,\"pulseOff\":40}","payloadType":"json","x":110,"y":380,"wires":[["41aabc6e.0deef4"]]},{"id":"abbdc4f9.ce9ec8","type":"inject","z":"bc7d6333.6da43","name":"PWM_0","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pwm","payload":"{\"channel\":0,\"pulseOn\":3000,\"pulseOff\":40}","payloadType":"json","x":110,"y":140,"wires":[["41aabc6e.0deef4"]]},{"id":"376cb74e.39c088","type":"inject","z":"bc7d6333.6da43","name":"PWM_1","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pwm","payload":"{\"channel\":1,\"pulseOn\":3000,\"pulseOff\":40}","payloadType":"json","x":110,"y":180,"wires":[["41aabc6e.0deef4"]]},{"id":"5fe7e787.0dccb8","type":"inject","z":"bc7d6333.6da43","name":"PWM_4","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pwm","payload":"{\"channel\":4,\"pulseOn\":3000,\"pulseOff\":40}","payloadType":"json","x":110,"y":300,"wires":[["41aabc6e.0deef4"]]},{"id":"6dbba87c.c16e18","type":"inject","z":"bc7d6333.6da43","name":"PWM_5","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pwm","payload":"{\"channel\":5,\"pulseOn\":3000,\"pulseOff\":40}","payloadType":"json","x":110,"y":340,"wires":[["41aabc6e.0deef4"]]},{"id":"60a9aa8c.7c0674","type":"inject","z":"bc7d6333.6da43","name":"PWM_3","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pwm","payload":"{\"channel\":3,\"pulseOn\":3000,\"pulseOff\":40}","payloadType":"json","x":110,"y":260,"wires":[["41aabc6e.0deef4"]]},{"id":"9fbf8370.352b8","type":"inject","z":"bc7d6333.6da43","name":"PWM_2","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pwm","payload":"{\"channel\":2,\"pulseOn\":3000,\"pulseOff\":40}","payloadType":"json","x":110,"y":220,"wires":[["41aabc6e.0deef4"]]},{"id":"71424a94.388f14","type":"inject","z":"bc7d6333.6da43","name":"Stop All","props":[{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"stop","x":110,"y":500,"wires":[["41aabc6e.0deef4"]]},{"id":"58f73b.9de8f8c4","type":"inject","z":"bc7d6333.6da43","name":"Set PWM Frequency","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"set_pwm_frequency","payload":"60","payloadType":"num","x":150,"y":540,"wires":[["41aabc6e.0deef4"]]},{"id":"142bdd21.108913","type":"inject","z":"bc7d6333.6da43","name":"PWM_0_PULSE","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pulse","payload":"{\"channel\":0,\"pulse\":5}","payloadType":"json","x":380,"y":20,"wires":[["41aabc6e.0deef4"]]},{"id":"4618979b.6f4b58","type":"inject","z":"bc7d6333.6da43","name":"PWM_7_PULSE","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pulse","payload":"{\"channel\":7,\"pulse\":50}","payloadType":"json","x":380,"y":300,"wires":[["41aabc6e.0deef4"]]},{"id":"b9fb682e.c81948","type":"inject","z":"bc7d6333.6da43","name":"PWM_6_PULSE","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pulse","payload":"{\"channel\":6,\"pulse\":50}","payloadType":"json","x":380,"y":260,"wires":[["41aabc6e.0deef4"]]},{"id":"e9924c2c.fa063","type":"inject","z":"bc7d6333.6da43","name":"PWM_5_PULSE","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pulse","payload":"{\"channel\":5,\"pulse\":50}","payloadType":"json","x":380,"y":220,"wires":[["41aabc6e.0deef4"]]},{"id":"b7d40b7.1d1c2f8","type":"inject","z":"bc7d6333.6da43","name":"PWM_4_PULSE","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pulse","payload":"{\"channel\":4,\"pulse\":50}","payloadType":"json","x":380,"y":180,"wires":[["41aabc6e.0deef4"]]},{"id":"95ecaeee.71b95","type":"inject","z":"bc7d6333.6da43","name":"PWM_3_PULSE","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pulse","payload":"{\"channel\":3,\"pulse\":50}","payloadType":"json","x":380,"y":140,"wires":[["41aabc6e.0deef4"]]},{"id":"87a12632.d96cd8","type":"inject","z":"bc7d6333.6da43","name":"PWM_2_PULSE","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pulse","payload":"{\"channel\":2,\"pulse\":50}","payloadType":"json","x":380,"y":100,"wires":[["41aabc6e.0deef4"]]},{"id":"6778b02e.7a59a","type":"inject","z":"bc7d6333.6da43","name":"PWM_1_PULSE","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"channel_pulse","payload":"{\"channel\":1,\"pulse\":50}","payloadType":"json","x":380,"y":60,"wires":[["41aabc6e.0deef4"]]},{"id":"42258af4.14e0e4","type":"ncd-comm","name":"PCA1","bus":"COM6","busManual":"","commType":"ncd-usb","addr":"0","useMux":false,"muxAddr":"112","muxPort":"0"}]

**Pull request merged**
